### ISSUE TITLE
Example of how to send event to google analytics from cinder app?

### ISSUE THREAD

**Issue by richardeakin** [stimulant/ampm#17]
Hi there, and thanks for this project, it looks very good for installations.  I'm currently reviewing some options for how we can integrate google analytics into our application and I noticed that your README has a section on [Event Tracking](https://github.com/stimulant/ampm#integration-events). Is there any example code that makes use of this? Particularly, I'm wondering how the payload should be sent over OSC from within a cinder app, as it looks like the expected payload is a JSON / JS object.

Thanks again!
Rich

**Comment by endquote** [comment]
See `AMPMClient::sendEvent`.

https://github.com/stimulant/ampm/blob/master/samples/Cinder/Client/src/AMPMClient.cpp#L77

https://github.com/stimulant/ampm/blob/master/samples/Cinder/Client/src/ClientApp.cpp#L64

**Comment by richardeakin** [comment]
Ah, cool! didn't notice it in the sample you've got up there already. Thanks so much, looking forward to giving this a spin.
