### ISSUE TITLE
Mac Cinder sample, error running server: "env: node\r: No such file or directory"

### ISSUE THREAD

**Issue by richardeakin** [stimulant/ampm#18]
This is probably something simple, reading around it might be because one of the script files has a windows-style carriage return? I'm extremely unfamiliar with node, so opening this here.

When I follow the directions for the Cinder sample and run `ampm` from the `samples/Cinder` directory on Mac OS X, this is what I get:

```bash
[r@Richs-MacBook-Pro Cinder (master *)]$ ampm ampm.mac.json
env: node\r: No such file or directory
```

**Comment by endquote** [comment]
Yeah, there's a line ending issue in start.js that keeps creeping in. I won't be in front of a computer for a week, so won't be able to look right away. You may be able to convert the line endings on your local copy of that file to fix.

**Comment by richardeakin** [comment]
Okay cool. Actually, I only saw the problem on when using ampm from npm package manager - using the local version worked great, and I'm up and running.

**Comment by endquote** [comment]
Are you still seeing this issue? I pushed a new version to npm with some other fixes, and then tried installing it on both Windows and Mac, and it worked ok as a global `ampm` command.
