### ISSUE TITLE
Defining "macosx" config within main ampm.json

### ISSUE THREAD

**Issue by richardeakin** [stimulant/ampm#20]
I was wondering if its possible to define a config mode for different platforms within the main ampm.json file, it seems like I should be able to from your readme but I haven't yet figured out how.

Basically, I'd like the "default" section to define how the app would run on our production PC, and then the "macosx" mode would just override the minimal amount to run the appropriate app on that platform (I'm overriding all of "persistence", would hopefully only have to override persistence.launchCommand). This is some example config:

```json
{
    "default": {
        "persistence": {
            "launchCommand": "../../applications/MyApp/vc2013/build/x64/RelWithDebInfo/MyApp.exe",
            "maxMemory": 0,
            "startupTimeout": 10,
            "heartbeatTimeout": 5
        },
        "permissions": {
            "user": {
                "password": "pw",
                "app": true,
                "computer": true
            }
        },
        "logging": {
            "file": {
                "filename": "logs/server"
            }
        }
    },
    "macosx": {
        "persistence": {
            "launchCommand": "../../applications/MyApp/xcode/build/Debug/MyApp.app/Contents/MacOS/MyApp",
            "maxMemory": 0,
            "startupTimeout": 10,
            "heartbeatTimeout": 5
        }
    }
}
```

When I try to run `ampm macosx`, it looks like nothing in the "persistence" sectio is set, so no launchCommand. Am I misunderstanding how this is supposed to work?

**Comment by LRitesh** [comment]
You'll have to mention the config file name as well. So something like:

`ampm ampm.json macosx`

should work.

**Comment by richardeakin** [comment]
Ah, ok great that seems to do the trick.

Am I right in thinking that the served up config doesn't contain a "permissions" section because of security reasons? Just sanity checking what is and isn't there when I run the alternate mode.

**Comment by endquote** [comment]
Yes, permissions is omitted on purpose for security reasons.
