### ISSUE TITLE
Possible to update "heartbeatTimeout" from app via OSC?

### ISSUE THREAD

**Issue by richardeakin** [stimulant/ampm#41]
I've got a tricky situation in our app where we know that the main update loop is going to snag for a long period of time while loading data, perhaps a couple minutes or so. Would it be possible to set the "heartbeatTimeout" longer for this duration, and then decrease it something much more responsive after the load is complete?

My understanding is that this is different to "startupTimeout", because I have actually already started up and it is now in a 'loading data from remote server' phase, but isn't yet interactive.

**Comment by endquote** [comment]
I think you should be able to do this by writing a [plugin](https://github.com/stimulant/ampm#configuration-plugin). In the plugin you could modify `$$config.persistence.heartbeatTimeout` in response to websocket or OSC commands. You don't need to make a new websocket or OSC socket, you can use the existing ones on the `$$network.transports` object.

Though it would also be worth exploring putting your long-running operation on a thread other than your main UI loop.

**Comment by endquote** [comment]
Closing, let me know if this is still an issue.

**Comment by richardeakin** [comment]
Ah good to know. I ended up spinning up a thread to send out heartbeats every second until the data finishes loading, unfortunately I wasn't in a position to rework that portion of the code (and didn't write it), but that got it past the initial hiccup.
