### ISSUE TITLE
Bad path to server.js, in start.js. ampm never starts

### ISSUE THREAD

**Issue by blakerutledge** [stimulant/ampm#46]
First, this is an amazing tool, thank you so much!

I implemented on an OSX project, all smooth. Now I've migrated the app over to Windows 10, and am running into issues with ampm. The ampm server fails to start properly, and just loops trying to. I've found I can resolve the issue by altering the ampm module's source code in the following way:

**start.js, line 27**
from: `server = path.join(path.dirname(server), 'node_modules', 'ampm', 'server.js');`
to:      `server = path.join(path.dirname(server), '..', 'ampm', 'server.js');`

My value for `server` as returned by the child process on line 26 is:
`C:\Users\path\to\application\node_modules\.bin\ampm.cmd`,

Interestingly, my value for `server` as of line 20 (start.js), is valid on both OSX & Windows (so everything works if I comment out lines 26 & 27). 

I've installed my modules using Yarn. Could that be using the .bin differently than normal npm installs? Not sure what the real solution to this is exactly. I can certainly fork the module for my needs but would rather have a proper fix either with the way I'm using ampm or with the official module itself. Thanks!

**Comment by blakerutledge** [comment]
Both point to the .bin executables:

where nodemon: `C:\Users\path\to\application\node_modules\.bin\nodemon.cmd`
where ampm: `C:\Users\path\to\application\node_modules\.bin\ampm.cmd`

**Comment by endquote** [comment]
Did you install ampm and nodemon globally? Whatever the yarn equivalent of `npm install -g ampm` is.

**Comment by blakerutledge** [comment]
I've tried both global and local installs, both fail. The above situation I was describing is with local installs. Would prefer to keep things self contained, I know you guys specify global in the setup docs but it was working with local installs on OSX, and then with my above fix on Windows 10.

And FYI it's `yarn global add ampm` :)

**Comment by endquote** [comment]
I took another look at this.

This code block is meant to solve an issue with spaces in paths on Windows, and it assumes that both `ampm` and `nodemon` are installed globally. Yarn stores global packages in a different place, so it blows up if it's installed with Yarn.

This seems like a fix:

```javascript
if (process.platform === 'win32') {
    // Gotta go to great lengths to avoid spaces in the path.
    // https://github.com/nodejs/node-v0.x-archive/issues/25895
    cmd = child_process.execSync('where nodemon').toString().split('\n')[1].replace('Program Files', 'PROGRA~1').trim();
    server = child_process.execSync('where ampm').toString().split('\n')[1].replace('Program Files', 'PROGRA~1').trim();
    server = path.dirname(server);
    if(server.toLowerCase().indexOf('yarn') !== -1) {
        server = path.join(server, '..', 'config', 'global');
    }
    server = path.join(server, 'node_modules', 'ampm', 'server.js');
}
```

I agree with you that installing stuff locally is a good way to go, and ampm should support being installed locally, but it currently doesn't. (I'm surprised that it works being installed locally on Mac...)

If you apply this patch to `C:\Users\username\AppData\Local\Yarn\config\global\node_modules\ampm\start.js`, does it resolve your issue?

**Comment by blakerutledge** [comment]
The patch works!

I'll resolve this issue -- however the local installation is going to be a requirement for my project. Do you already have that update scoped out? I assume that change has larger implications and requires a good deal of testing on your end.. I'll plan on forking and using my modified version that works with local ampm & nodemon installs. Let me know if that change comes any time soon! thank you man
