### ISSUE TITLE
Java Application Monitoring

### ISSUE THREAD

**Issue by Obsidian1269** [stimulant/ampm#52]
Hey so I'm trying to configure this to work with a java-based server and am running into issues. I am passing a number of arguments to java and launching the .jar file via batch file on windows. If I use ampm to launch the batch file, it starts up but ampm doesn't acknowledge the .jar executable as I believe it only takes into account the batch file itself (.bat). What happens is ampm keeps trying to launch the .bat file over and over again rather than track and monitor the .jar. How can I reliably launch and monitor a .jar file while ensuring I can also pass arguments to it? Also I realize the project is rather old at this point so no worries if no one is still maintaining these forums. Thanks for making this!

**Comment by endquote** [comment]
Sorry for just now seeing this.

I don't think running the batch file will work, since it will probably run, spawn whatever is in the script, then exit. Then ampm will launch it again.

You could try [associating the jar with the JRE](https://stackoverflow.com/a/8511277/468472), and then run the jar directly.

Or run `javaw.exe` along with whatever arguments you need.

**Comment by Obsidian1269** [comment]
Thanks for the prompt reply! Yeah that was my impression of what was
happening.

I will attempt to try those methods and see if it works. FYI this is for a
remote minecraft server.

Curious if there is a definite need for heartbeat reporting in order for
this to function properly. Fearing that's a hard yes.

Still planning to utilize this in a Unity project as well so I'll find a
use for it either way!

**Comment by endquote** [comment]
If you don’t need ampm’s features, there are other things to try. 

https://www.softpedia.com/get/System/File-Management/Restart-on-Crash.shtml

https://github.com/bantherewind/StayUp
